name: Release to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          server-id: github
          distribution: 'temurin'
          cache: maven
 
      - name: Set Release Version
        id: vars
        shell: bash
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          mvn -ntp --batch-mode versions:set -DnewVersion=${{ github.event.inputs.version }}
          git diff-index --quiet HEAD || git commit -m "Releasing version ${{ github.event.inputs.version }}" pom.xml
        
      - name: Publish to GitHub Packages
        run: mvn -ntp --batch-mode clean deploy -Prelease
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set up Java for publishing to Maven Central
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to the Maven Central
        run: mvn --batch-mode deploy -Prelease,mavencentral-release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
