name: Release to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          server-id: github
          distribution: 'temurin'
          cache: maven
 
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
 
      - name: Set Release Version
        id: vars
        shell: bash
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo ${{ github.event.inputs.version }} > VERSION
          mvn versions:set -DnewVersion=${{ github.event.inputs.version }}-SNAPSHOT
          git commit -m "Releasing version ${{ github.event.inputs.version }}" pom.xml
          git push origin main
        
      - name: Publish to GitHub Packages
        run: mvn -ntp -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Create a GitHub Release
      # TODO (oleg-nenashev): Consider switching to Release Drafter if there is not significant value except fancy changelog
      # ... So far we do not plan to automate release announcements, and artifacts can be attached to the release via another step
      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.version }}

      # Persist JReleaser logs
      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
 
