name: Release to GitHub Packages

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          server-id: github
          distribution: 'temurin'
          cache: maven
 
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
 
 #     - name: Setup Git user
 #       uses: fregante/setup-git-user@v2 
 #       
#      - name: Setup SSH Keys and known_hosts
#        env:
#          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
#        run: |
#            mkdir -p ~/.ssh
#            ssh-keyscan github.com >> ~/.ssh/known_hosts
#            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
#            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        
      - name: Publish to GitHub Packages
        run: mvn -ntp -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Create a release
      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Persist JReleaser logs
      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
 
